# Generated by Django 4.2.6 on 2024-02-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_flower_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="flower",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
