# Generated by Django 4.2.6 on 2024-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="flower",
            name="tag",
            field=models.ManyToManyField(to="myapp.tag"),
        ),
    ]
