# Generated by Django 4.2.6 on 2024-02-06 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_flower_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flower",
            old_name="tag",
            new_name="tags",
        ),
    ]
