# Generated by Django 4.2.6 on 2024-02-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_rename_tag_flower_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
